/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pos.remade;

import business.addToBillHelper;
import business.checkForStockHelper;
import business.deleteHelper;
import business.TSI;
import java.awt.Component;
import java.awt.Desktop;
import java.awt.print.PrinterJob;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.List;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;


/**
 *
 * @author ianschrauth
 */
public class POSScreenUser extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public POSScreenUser() {

        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jButton17 = new javax.swing.JButton();
        price = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        taw_bttn = new javax.swing.JButton();
        the_opportunity_button = new javax.swing.JButton();
        TSLSMBODH_bttn = new javax.swing.JButton();
        vbab1_bttn = new javax.swing.JButton();
        vbab2_bttn = new javax.swing.JButton();
        vbab3_bttn = new javax.swing.JButton();
        vbab123_bttn = new javax.swing.JButton();
        cmm1_bttn = new javax.swing.JButton();
        cmm2_bttn = new javax.swing.JButton();
        trace_my_steps_button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        custom = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        fful1_bttn1 = new javax.swing.JButton();
        tify_bttn = new javax.swing.JButton();
        fful2_bttn2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        BTV_bttn2 = new javax.swing.JButton();
        tseventy_bttn = new javax.swing.JButton();
        tms_bttn = new javax.swing.JButton();
        SLMPD_bttn = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Book title", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table);

        jButton17.setText("Delete");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        price.setText("0.00");

        jButton4.setText("Pay now");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("FPK");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        taw_bttn.setText("TAW");
        taw_bttn.setEnabled(false);
        taw_bttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taw_bttnActionPerformed(evt);
            }
        });

        the_opportunity_button.setText("TO");
        the_opportunity_button.setEnabled(false);
        the_opportunity_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                the_opportunity_buttonActionPerformed(evt);
            }
        });

        TSLSMBODH_bttn.setText("TSLSMBODH");
        TSLSMBODH_bttn.setEnabled(false);
        TSLSMBODH_bttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TSLSMBODH_bttnActionPerformed(evt);
            }
        });

        vbab1_bttn.setText("VBAB1");
        vbab1_bttn.setEnabled(false);
        vbab1_bttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vbab1_bttnActionPerformed(evt);
            }
        });

        vbab2_bttn.setText("VBAB2");
        vbab2_bttn.setEnabled(false);
        vbab2_bttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vbab2_bttnActionPerformed(evt);
            }
        });

        vbab3_bttn.setText("VBAB3");
        vbab3_bttn.setEnabled(false);
        vbab3_bttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vbab3_bttnActionPerformed(evt);
            }
        });

        vbab123_bttn.setText("VBAB123");
        vbab123_bttn.setEnabled(false);
        vbab123_bttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vbab123_bttnActionPerformed(evt);
            }
        });

        cmm1_bttn.setText("CMM1");
        cmm1_bttn.setEnabled(false);
        cmm1_bttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmm1_bttnActionPerformed(evt);
            }
        });

        cmm2_bttn.setText("CMM2");
        cmm2_bttn.setEnabled(false);
        cmm2_bttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmm2_bttnActionPerformed(evt);
            }
        });

        trace_my_steps_button.setText("VBAB123 - H");
        trace_my_steps_button.setEnabled(false);
        trace_my_steps_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trace_my_steps_buttonActionPerformed(evt);
            }
        });

        jLabel1.setText("Custom price");

        custom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customActionPerformed(evt);
            }
        });

        jButton8.setText("Add to total");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        fful1_bttn1.setText("FFUL1");
        fful1_bttn1.setEnabled(false);
        fful1_bttn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fful1_bttn1ActionPerformed(evt);
            }
        });

        tify_bttn.setText("TIFY");
        tify_bttn.setEnabled(false);
        tify_bttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tify_bttnActionPerformed(evt);
            }
        });

        fful2_bttn2.setText("FFUL2");
        fful2_bttn2.setEnabled(false);
        fful2_bttn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fful2_bttn2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(custom, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton8))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(vbab1_bttn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vbab2_bttn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vbab3_bttn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(vbab123_bttn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(trace_my_steps_button))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cmm1_bttn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmm2_bttn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tify_bttn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fful1_bttn1)
                        .addGap(18, 18, 18)
                        .addComponent(fful2_bttn2)))
                .addGap(0, 90, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(taw_bttn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(the_opportunity_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TSLSMBODH_bttn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vbab1_bttn, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vbab2_bttn, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vbab3_bttn, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vbab123_bttn, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(trace_my_steps_button, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmm1_bttn, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmm2_bttn, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tify_bttn, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(fful1_bttn1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(fful2_bttn2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(taw_bttn, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(the_opportunity_button, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TSLSMBODH_bttn, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 164, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(custom, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8))
                .addContainerGap())
        );

        jTabbedPane1.addTab("HeartStone VS", jPanel1);

        BTV_bttn2.setText("BTV");
        BTV_bttn2.setEnabled(false);
        BTV_bttn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTV_bttn2ActionPerformed(evt);
            }
        });

        tseventy_bttn.setText("270");
        tseventy_bttn.setEnabled(false);
        tseventy_bttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tseventy_bttnActionPerformed(evt);
            }
        });

        tms_bttn.setText("TMS");
        tms_bttn.setEnabled(false);
        tms_bttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tms_bttnActionPerformed(evt);
            }
        });

        SLMPD_bttn.setText("SLMPD");
        SLMPD_bttn.setEnabled(false);
        SLMPD_bttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SLMPD_bttnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tseventy_bttn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BTV_bttn2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tms_bttn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SLMPD_bttn)
                .addContainerGap(203, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTV_bttn2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tseventy_bttn, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tms_bttn, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SLMPD_bttn, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(340, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Pocket Reads", jPanel2);

        jMenu2.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem1.setText("Admin menu (BETA)");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_BACK_SPACE, 0));
        jMenuItem2.setText("Clear");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem4.setText("(NOT FINISHED) Finalize event");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("Stock");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuItem11.setText("Reprint receipt");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem11);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Discounts list");

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem3.setText("100%");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(price)
                            .addGap(44, 44, 44)
                            .addComponent(jButton4)
                            .addGap(48, 48, 48))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap()))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jButton17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5)
                        .addGap(24, 24, 24))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton4)
                            .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton17)
                            .addComponent(jButton5))))
                .addGap(0, 10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //https://docs.google.com/spreadsheets/u/0/d/1Nvarm3CjxAKuccnEp_RqUfrvKwUiXLsd_vJ8Ts5rap0/export?format=csv&id=1Nvarm3CjxAKuccnEp_RqUfrvKwUiXLsd_vJ8Ts5rap0&gid=0


//   static int arc = 0, customP = 0, piatw = 0, cmm = 0, tifu2c = 0, ciatw = 0, biatw = 0, vbab1 = 0, vbab2 = 0, vbab3 = 0, tifu = 0, tifu2 = 0, tgwtf = 0, dil = 0, bella = 0, nia = 0, iihy = 0 , vbabss = 0;
//    static int Sarc, Ssiatw, Spiatw, Scmm, Stifu2c, Sciatw, Sbiatw, Svbab1, Svbab2, Svbab3, Stifu, Stifu2, Stgwtf, Sdil, Sbella, Snia, Siihy, Svbabss;

    static String name;

    int pl = -1;
    static double allSales = 0.00;



    Object[] row;
    int NOR = 0;
    double change2 = Math.round(allSales * 1000.0) / 1000.0;
   
    
    prices p =  new prices();

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        // model,  numRows2,  row,  priceToRemove,  masterPrice,  CopiesOfbooksSold,  stockAmmt,  button,  priceLabel
        
        

        int numRows2 = table.getSelectedRows().length;

        int row = table.getSelectedRow();

        String numToDel = table.getValueAt(row, 1).toString();
        
        double priceToRemove = Double.parseDouble(numToDel);

 System.out.println(priceToRemove);

        

        switch (table.getModel().getValueAt(row, 0).toString()) {
            case "Vacillating Brown and Black: Vol. 1 - 3 (Hardcover)": //change to hardback vbab123
           deleteHelper.delete(model, numRows2, row, priceToRemove, TSI.BILL_TOTAL, TSI.INVENTORY_H_VBAB123, TSI.STOCK_H_VBAB123, null, price);
break;
     
                 //add deletehelper

        
            case "The Opportunity (softcover)":
                    deleteHelper.delete(model, numRows2, row, priceToRemove, TSI.BILL_TOTAL, TSI.INVENTORY_TO_gen, TSI.STOCK_TO_gen, the_opportunity_button, price);
              break;

            case "Trace My Steps (Softcover)":
                   deleteHelper.delete(model, numRows2, row, priceToRemove, TSI.BILL_TOTAL, TSI.INVENTORY_TMS, TSI.STOCK_TMS, null, price);
break;
            

            case "Vacillating Brown and Black: Vol. 1 (Softcover)":
            deleteHelper.delete(model, numRows2, row, priceToRemove, TSI.BILL_TOTAL, TSI.INVENTORY_VBAB1, TSI.STOCK_VBAB1, vbab1_bttn, price);
              break;

            case "Vacillating Brown and Black: Vol. 2 (Softcover)":
               deleteHelper.delete(model, numRows2, row, priceToRemove, TSI.BILL_TOTAL, TSI.INVENTORY_VBAB2, TSI.STOCK_VBAB2, vbab2_bttn, price);
              break;

            case "Vacillating Brown and Black: Vol. 3 (Softcover)":
                deleteHelper.delete(model, numRows2, row, priceToRemove, TSI.BILL_TOTAL, TSI.INVENTORY_VBAB3, TSI.STOCK_VBAB3, vbab3_bttn, price);
              break;
           case "Vacillating Brown and Black: Vol. 1 - 3 (Softcover)":
                deleteHelper.delete(model, numRows2, row, priceToRemove, TSI.BILL_TOTAL, TSI.INVENTORY_VBAB123, TSI.STOCK_VBAB123, vbab123_bttn, price);
              break;
           case "Call me maybe: Vol. 1 (Softcover)":
            deleteHelper.delete(model, numRows2, row, priceToRemove, TSI.BILL_TOTAL, TSI.INVENTORY_CMM1, TSI.STOCK_CMM1, cmm1_bttn, price);
              break;
            case "Call me maybe: Vol. 2 (softcover)":
            deleteHelper.delete(model, numRows2, row, priceToRemove, TSI.BILL_TOTAL, TSI.INVENTORY_CMM2, TSI.STOCK_CMM2, cmm2_bttn, price);
              break;

       case "Faithful: Vol. 1 (Softcover)":
            deleteHelper.delete(model, numRows2, row, priceToRemove, TSI.BILL_TOTAL, TSI.INVENTORY_FFUL1, TSI.STOCK_FFUL1, fful1_bttn1, price);
              break;
      case "Faithful: Vol. 2 (Softcover)":
            deleteHelper.delete(model, numRows2, row, priceToRemove, TSI.BILL_TOTAL, TSI.INVENTORY_FFUL2, TSI.STOCK_FFUL2, fful2_bttn2, price);
              break;
              
                    case "Till I Find You (Softcover)":
            deleteHelper.delete(model, numRows2, row, priceToRemove, TSI.BILL_TOTAL, TSI.INVENTORY_TIFY, TSI.STOCK_TIFY, tify_bttn, price);
              break;

           case "270 (softcover)":
              deleteHelper.delete(model, numRows2, row, priceToRemove, TSI.BILL_TOTAL, TSI.INVENTORY_270_paperback, TSI.STOCK_270_paperback, tseventy_bttn, price);
              break;
        
              
              
                case "The American Way":
              deleteHelper.delete(model, numRows2, row, priceToRemove, TSI.BILL_TOTAL, TSI.INVENTORY_TAW, TSI.STOCK_TAW, taw_bttn, price);
              break;
              
              
                case "Beyond the Veil":
              deleteHelper.delete(model, numRows2, row, priceToRemove, TSI.BILL_TOTAL, TSI.INVENTORY_BTV, TSI.STOCK_BTV, BTV_bttn2, price);
              break;
              
              
              
                case "TSLSMBODH":
              deleteHelper.delete(model, numRows2, row, priceToRemove, TSI.BILL_TOTAL, TSI.INVENTORY_TSLSMBODH, TSI.STOCK_TSLSMBODH, TSLSMBODH_bttn, price);
              break;
 
            default:
                Component frame = null;
            JOptionPane.showMessageDialog(frame, "Nothing is selcted.");
            break;
            
            
        }
    


        model.removeRow(row);
        model.fireTableDataChanged();

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        dispose();
        new adminMenu().setVisible(true);        // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed
    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        DefaultTableModel model = (DefaultTableModel) table.getModel();

        TSI.BILL_TOTAL = 0.00;
        price.setText("0.00");
        model.setRowCount(0);
        model.fireTableDataChanged();
        model.fireTableStructureChanged();
        // TODO add your handling code here:
        ;
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        BufferedReader in = null;
        BufferedWriter writer = null;

        try {
            adminMenu admin = new adminMenu();
            DefaultTableModel model = (DefaultTableModel) table.getModel();
            String st = "names.csv";
            writer = new BufferedWriter(new FileWriter(st));
            in = new BufferedReader(new FileReader(st));
            String s;
            String lineToRemove = "";
            String currentLine = null;

            while ((s = in.readLine()) != null) {
                for (int i = 0; i < s.length(); i++) {
                    if (s.contains(lineToRemove)) {
                        String trimmedLine = currentLine.trim();
                        if (trimmedLine.equals(lineToRemove)) {
                            continue;
                        }
                        writer.write(currentLine + System.getProperty("line.separator"));
                        writer.close();
                        break;
                    }
                }
            }
            try (BufferedWriter bw = new BufferedWriter(new FileWriter("finalize.txt", true))) {
//                bw.write("FINALIZING COMPLETE! THIS IS YOUR PROGRESS: \r\n \r\n HOW MUCH YOU MADE: " + admin.all + " \r\n PIATW: " + TSI.INVENTORY_PIATW
//                        + "\r\n CIATW: " + TSI.INVENTORY_CIATW + "\r\n BIATW: " + TSI.INVENTORY_BIATW + "\r\n VBAB1: " + TSI.INVENTORY_VBAB1 + "\r\n VBAB2: " + TSI.INVENTORY_VBAB2
//                        + "\r\n VBAB3: " + TSI.INVENTORY_VBAB3 + "\r\n TIFU: " + TSI.INVENTORY_TIFY + "\r\n TIFU2: " + TSI.INVENTORY_TIFY2 + "\r\n TGWTF: " + TSI.INVENTORY_TGWTF
//                        + "\r\n IIHU: " + TSI.INVENTORY_IIHY +   "\r\n CMM: " + TSI.INVENTORY_CMM);

                Desktop.getDesktop().print(new File("finalize.txt"));
//                createStockCSV();

                System.out.println("Done");

                // TODO add your handling code here:
            } catch (IOException ex) {
                Logger.getLogger(POSScreenUser.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(POSScreenUser.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(POSScreenUser.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                in.close();
            } catch (IOException ex) {
                Logger.getLogger(POSScreenUser.class.getName()).log(Level.SEVERE, null, ex);
            }
        }


    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        DefaultTableModel model = (DefaultTableModel) table.getModel();

        model.setRowCount(0);
        model.fireTableDataChanged();
        model.fireTableStructureChanged();

        if (TSI.BILL_TOTAL == 0) {
            Component frame = null;
            JOptionPane.showMessageDialog(frame, "Total is Zero. No need to cash out.");
            model.setRowCount(0);
            TSI.BILL_TOTAL = 0.00;
            price.setText("0.00");
            model.fireTableDataChanged();
        } else {

            new payment2().setVisible(true);
            setVisible(false);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
           
  DefaultTableModel model = (DefaultTableModel) table.getModel();
        
        
        addToBillHelper atbHelper = new addToBillHelper();

        atbHelper.addToTable(model, "CUSTOM PRICE", Double.parseDouble(custom.getText()), price);
       
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void customActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        new inventory().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        DefaultTableModel model = (DefaultTableModel) table.getModel();

        checkForStockHelper.checkForStock(TSI.INVENTORY_TO_gen , the_opportunity_button);
//    checkForStockHelper.checkForStock(TSI.INVENTORY_TO_bookClub , XXX);
//            checkForStockHelper.checkForStock(TSI.INVENTORY_TO_WithNovelette , XXX);
//                    checkForStockHelper.checkForStock(TSI.INVENTORY_TO_dustJacket , XXX);
                        
//the opportunity, part II and editions
checkForStockHelper.checkForStock(TSI.INVENTORY_TMS , trace_my_steps_button);
//  checkForStockHelper.checkForStock(TSI.INVENTORY_TO2_dustJacket , XXX);
//checkForStockHelper.checkForStock(TSI.INVENTORY_TO2_bookClub , XXX);

    
    


        //270 and editions
    checkForStockHelper.checkForStock(TSI.INVENTORY_270_paperback , tseventy_bttn);
//        checkForStockHelper.checkForStock(TSI.INVENTORY_270_hardcover , XXX);

    //books without other editions
checkForStockHelper.checkForStock(TSI.INVENTORY_TSLSMBODH , TSLSMBODH_bttn);
checkForStockHelper.checkForStock(TSI.INVENTORY_VBAB1 , vbab1_bttn);
checkForStockHelper.checkForStock(TSI.INVENTORY_VBAB2 , vbab2_bttn);
checkForStockHelper.checkForStock(TSI.INVENTORY_VBAB3 , vbab3_bttn);
checkForStockHelper.checkForStock(TSI.INVENTORY_VBAB123 , vbab123_bttn);
    
checkForStockHelper.checkForStock(TSI.INVENTORY_CMM1 , cmm1_bttn);
checkForStockHelper.checkForStock(TSI.INVENTORY_CMM2 , cmm2_bttn);


checkForStockHelper.checkForStock(TSI.INVENTORY_TAW , taw_bttn);
checkForStockHelper.checkForStock(TSI.INVENTORY_BTV, BTV_bttn2);

    checkForStockHelper.checkForStock(TSI.INVENTORY_H_VBAB123, BTV_bttn2);


        
    }//GEN-LAST:event_formWindowOpened

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        DefaultTableModel model = (DefaultTableModel) table.getModel();

        if (model.getRowCount() == 0) {

            TSI.BILL_TOTAL = 0.00;
            price.setText("0.00");

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        int col0 = 0;
        int col1 = 1;
        

        int numRows2 = table.getSelectedRows().length;
        int row = table.getSelectedRow();
        Component frame = null;
        if (table.getModel().getValueAt(row, 0).equals("0.00")) {
            JOptionPane.showMessageDialog(frame, "You already set it to free. delete \r\n the book and re-add it to take off the promo.");
        }
        for (int count = 0; count < model.getRowCount(); count++) {

            TSI.BILL_TOTAL -= (Double) table.getValueAt(row, 1);;
    
            System.out.println(TSI.BILL_TOTAL);
            price.setText(Double.toString(TSI.BILL_TOTAL));

            model.fireTableDataChanged();

            break;

        }
        table.getModel().setValueAt((Double) 0.00, row, 1);

// TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        new reprint().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        DefaultTableModel model = (DefaultTableModel) table.getModel();

        String contentForReceipt = "IAN'S BOOK SIGNING RECEIPT \r\n Total: $0.00.  \r\n Was $" + TSI.BILL_TOTAL;

        try (BufferedWriter bw = new BufferedWriter(new FileWriter("receipt100.txt"))) {
            bw.write(contentForReceipt);

            //Desktop.getDesktop().print(new File("receipt100.txt"));
            System.out.println("Done");

            model.setRowCount(0);
            TSI.BILL_TOTAL = 0.00;
            price.setText("0.00");
            model.fireTableDataChanged();

        } catch (IOException ex) {
            Logger.getLogger(POSScreenUser.class.getName()).log(Level.SEVERE, null, ex);

        }        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void the_opportunity_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_the_opportunity_buttonActionPerformed

            
        
        
        
        DefaultTableModel model = (DefaultTableModel) table.getModel();

        addToBillHelper atbHelper = new addToBillHelper();

        atbHelper.addToTable(model, "The Opportunity (softcover)", p.PRICE_TO_gen, price);

TSI.INVENTORY_TO_gen = TSI.INVENTORY_TO_gen - 1;

        if (TSI.INVENTORY_TO_gen == 0) {
            the_opportunity_button.setEnabled(false);
        }   
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_the_opportunity_buttonActionPerformed

    private void TSLSMBODH_bttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TSLSMBODH_bttnActionPerformed

        
        
        DefaultTableModel model = (DefaultTableModel) table.getModel();

        addToBillHelper atbHelper = new addToBillHelper();

        atbHelper.addToTable(model, "TSLSMBODH", p.PRICE_TSLSMBODH, price);

TSI.INVENTORY_TSLSMBODH = TSI.INVENTORY_TSLSMBODH - 1;

        if (TSI.INVENTORY_TSLSMBODH == 0) {
           TSLSMBODH_bttn.setEnabled(false);
        }           // TODO add your handling code here:
    }//GEN-LAST:event_TSLSMBODH_bttnActionPerformed

    private void vbab1_bttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vbab1_bttnActionPerformed
 DefaultTableModel model = (DefaultTableModel) table.getModel();

        addToBillHelper atbHelper = new addToBillHelper();

        atbHelper.addToTable(model, "Vacillating Brown and Black: Vol. 1 (Softcover)", p.PRICE_VBAB1, price);

TSI.INVENTORY_VBAB1 = TSI.INVENTORY_VBAB1 - 1;

        if (TSI.INVENTORY_VBAB1 == 0) {
           vbab1_bttn.setEnabled(false);
        }          // TODO add your handling code here:
    }//GEN-LAST:event_vbab1_bttnActionPerformed

    private void vbab2_bttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vbab2_bttnActionPerformed
 DefaultTableModel model = (DefaultTableModel) table.getModel();

        addToBillHelper atbHelper = new addToBillHelper();

        atbHelper.addToTable(model, "Vacillating Brown and Black: Vol. 2 (Softcover)", p.PRICE_VBAB2, price);

TSI.INVENTORY_VBAB2 = TSI.INVENTORY_VBAB2 - 1;

        if (TSI.INVENTORY_VBAB2 == 0) {
           vbab2_bttn.setEnabled(false);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_vbab2_bttnActionPerformed

    private void vbab3_bttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vbab3_bttnActionPerformed
DefaultTableModel model = (DefaultTableModel) table.getModel();

        addToBillHelper atbHelper = new addToBillHelper();

        atbHelper.addToTable(model, "Vacillating Brown and Black: Vol. 3 (Softcover)", p.PRICE_VBAB3, price);

TSI.INVENTORY_VBAB3 = TSI.INVENTORY_VBAB3 - 1;

        if (TSI.INVENTORY_VBAB2 == 0) {
           vbab3_bttn.setEnabled(false);
        }          // TODO add your handling code here:
    }//GEN-LAST:event_vbab3_bttnActionPerformed

    private void vbab123_bttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vbab123_bttnActionPerformed
DefaultTableModel model = (DefaultTableModel) table.getModel();

        addToBillHelper atbHelper = new addToBillHelper();

        atbHelper.addToTable(model, "Vacillating Brown and Black: Vol. 1 - 3 (Softcover)", p.PRICE_VBAB123, price);

TSI.INVENTORY_VBAB123 = TSI.INVENTORY_VBAB123 - 1;

        if (TSI.INVENTORY_VBAB123 == 0) {
           vbab123_bttn.setEnabled(false);
        }          // TODO add your handling code here:
    }//GEN-LAST:event_vbab123_bttnActionPerformed

    private void cmm1_bttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmm1_bttnActionPerformed
DefaultTableModel model = (DefaultTableModel) table.getModel();

        addToBillHelper atbHelper = new addToBillHelper();

        atbHelper.addToTable(model, "Call me maybe: Vol. 1 (softcover)", p.PRICE_CMM1, price);

TSI.INVENTORY_CMM1 = TSI.INVENTORY_CMM1 - 1;

        if (TSI.INVENTORY_CMM1 == 0) {
           cmm1_bttn.setEnabled(false);
        }         // TODO add your handling code here:
    }//GEN-LAST:event_cmm1_bttnActionPerformed

    private void cmm2_bttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmm2_bttnActionPerformed
DefaultTableModel model = (DefaultTableModel) table.getModel();

        addToBillHelper atbHelper = new addToBillHelper();

        atbHelper.addToTable(model, "Call me maybe: Vol. 2 (softcover)", p.PRICE_CMM2, price);

TSI.INVENTORY_CMM2 = TSI.INVENTORY_CMM2 - 1;

        if (TSI.INVENTORY_CMM2 == 0) {
           cmm2_bttn.setEnabled(false);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_cmm2_bttnActionPerformed

    private void taw_bttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taw_bttnActionPerformed
DefaultTableModel model = (DefaultTableModel) table.getModel();

        addToBillHelper atbHelper = new addToBillHelper();

        atbHelper.addToTable(model, "The American Way", p.PRICE_TAW, price);

TSI.INVENTORY_TAW = TSI.INVENTORY_TAW - 1;

        if (TSI.INVENTORY_TAW == 0) {
           taw_bttn.setEnabled(false);
        }            // TODO add your handling code here:
    }//GEN-LAST:event_taw_bttnActionPerformed

    private void BTV_bttn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTV_bttn2ActionPerformed
DefaultTableModel model = (DefaultTableModel) table.getModel();

        addToBillHelper atbHelper = new addToBillHelper();

        atbHelper.addToTable(model, "Beyond the Veil", p.PRICE_BTV, price);

TSI.INVENTORY_BTV = TSI.INVENTORY_BTV - 1;

        if (TSI.INVENTORY_BTV == 0) {
           BTV_bttn2.setEnabled(false);
        } 
        // TODO add your handling code here:
    }//GEN-LAST:event_BTV_bttn2ActionPerformed

    private void tseventy_bttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tseventy_bttnActionPerformed
        
        DefaultTableModel model = (DefaultTableModel) table.getModel();

        addToBillHelper atbHelper = new addToBillHelper();

        atbHelper.addToTable(model, "270 (softcover)", p.PRICE_270_paperback, price);

TSI.INVENTORY_270_paperback = TSI.INVENTORY_270_paperback - 1;

        if (TSI.INVENTORY_270_paperback == 0) {
            tseventy_bttn.setEnabled(false);
        }          // TODO add your handling code here:
    }//GEN-LAST:event_tseventy_bttnActionPerformed

    private void tms_bttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tms_bttnActionPerformed
    DefaultTableModel model = (DefaultTableModel) table.getModel();

        addToBillHelper atbHelper = new addToBillHelper();

        atbHelper.addToTable(model, "Trace My Steps (Softcover)", p.PRICE_TMS, price);

        TSI.INVENTORY_TMS = TSI.INVENTORY_TMS - 1;

        if (TSI.INVENTORY_TMS == 0) {
            trace_my_steps_button.setEnabled(false);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_tms_bttnActionPerformed

    private void SLMPD_bttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SLMPD_bttnActionPerformed
  DefaultTableModel model = (DefaultTableModel) table.getModel();

        addToBillHelper atbHelper = new addToBillHelper();

        atbHelper.addToTable(model, "SLMPD 1", p.PRICE_SLMPD, price);

        TSI.INVENTORY_SLMPD = TSI.INVENTORY_SLMPD - 1;

        if (TSI.INVENTORY_SLMPD == 0) {
            SLMPD_bttn.setEnabled(false);
        }         // TODO add your handling code here:
    }//GEN-LAST:event_SLMPD_bttnActionPerformed

    private void trace_my_steps_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trace_my_steps_buttonActionPerformed
DefaultTableModel model = (DefaultTableModel) table.getModel();

        addToBillHelper atbHelper = new addToBillHelper();

        atbHelper.addToTable(model, "Vacillating Brown and Black: Vol. 1 - 3 (Hardcover)", p.PRICE_H_VBAB123, price);

TSI.INVENTORY_H_VBAB123 = TSI.INVENTORY_H_VBAB123 - 1;

        if (TSI.INVENTORY_H_VBAB123 == 0) {
          BTV_bttn2.setEnabled(false);
        }    

    
        // TODO add your handling code here:
    }//GEN-LAST:event_trace_my_steps_buttonActionPerformed

    private void fful1_bttn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fful1_bttn1ActionPerformed
 DefaultTableModel model = (DefaultTableModel) table.getModel();

        addToBillHelper atbHelper = new addToBillHelper();

        atbHelper.addToTable(model, "Faithful: Vol. 1 (Softcover)", p.PRICE_FFUL1, price);

TSI.INVENTORY_FFUL1 = TSI.INVENTORY_FFUL1 - 1;

        if (TSI.INVENTORY_FFUL1 == 0) {
           fful1_bttn1.setEnabled(false);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_fful1_bttn1ActionPerformed

    private void tify_bttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tify_bttnActionPerformed
DefaultTableModel model = (DefaultTableModel) table.getModel();

        addToBillHelper atbHelper = new addToBillHelper();

        atbHelper.addToTable(model, "Till I Find You (Softcover)", p.PRICE_TIFY, price);

TSI.INVENTORY_TIFY = TSI.INVENTORY_TIFY - 1;

        if (TSI.INVENTORY_TIFY == 0) {
           tify_bttn.setEnabled(false);
        }         // TODO add your handling code here:
    }//GEN-LAST:event_tify_bttnActionPerformed

    private void fful2_bttn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fful2_bttn2ActionPerformed
 DefaultTableModel model = (DefaultTableModel) table.getModel();

        addToBillHelper atbHelper = new addToBillHelper();

        atbHelper.addToTable(model, "Faithful: Vol. 2 (Software)", p.PRICE_FFUL2, price);

TSI.INVENTORY_FFUL2 = TSI.INVENTORY_FFUL2 - 1;

        if (TSI.INVENTORY_FFUL2 == 0) {
           fful2_bttn2.setEnabled(false);
        }          // TODO add your handling code here:
    }//GEN-LAST:event_fful2_bttn2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(POSScreenUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(POSScreenUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(POSScreenUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(POSScreenUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new POSScreenUser().setVisible(true);

            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTV_bttn2;
    private javax.swing.JButton SLMPD_bttn;
    private javax.swing.JButton TSLSMBODH_bttn;
    private javax.swing.JButton cmm1_bttn;
    private javax.swing.JButton cmm2_bttn;
    private javax.swing.JTextField custom;
    private javax.swing.JButton fful1_bttn1;
    private javax.swing.JButton fful2_bttn2;
    private javax.swing.JButton jButton17;
    public static javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    public javax.swing.JLabel price;
    public static javax.swing.JTable table;
    private javax.swing.JButton taw_bttn;
    private javax.swing.JButton the_opportunity_button;
    private javax.swing.JButton tify_bttn;
    private javax.swing.JButton tms_bttn;
    private javax.swing.JButton trace_my_steps_button;
    private javax.swing.JButton tseventy_bttn;
    private javax.swing.JButton vbab123_bttn;
    private javax.swing.JButton vbab1_bttn;
    private javax.swing.JButton vbab2_bttn;
    private javax.swing.JButton vbab3_bttn;
    // End of variables declaration//GEN-END:variables
//
//    private void createStockCSV() throws FileNotFoundException {
//        
//            java.util.Date date = new java.util.Date();
//
//        
//        PrintWriter pw = new PrintWriter(new File("PastStock" + date + ".csv"));
//        StringBuilder sb = new StringBuilder();
//        sb.append("BIATW");
//        sb.append(",");
//        sb.append(TSI.INVENTORY_BIATW);
//        sb.append("\n");
//        sb.append("CIATW");
//        sb.append(",");
//        sb.append(TSI.INVENTORY_CIATW);
//        sb.append("\n");
//        sb.append("PIATW");
//        sb.append(",");
//        sb.append(TSI.INVENTORY_PIATW);
//        sb.append("\n");
//        sb.append("VBAB1");
//        sb.append(",");
//        sb.append(TSI.INVENTORY_VBAB1);
//        sb.append("\n");
//        sb.append("VBAB2");
//        sb.append(",");
//        sb.append(TSI.INVENTORY_VBAB2);
//        sb.append("\n");
//        sb.append("VBAB3");
//        sb.append(",");
//        sb.append(TSI.INVENTORY_VBAB3);
//        sb.append("\n");
//        sb.append("VBABSS");
//        sb.append(",");
//        sb.append(TSI.INVENTORY_VBABSS);
//        sb.append("\n");
//        sb.append("CMM");
//        sb.append(",");
//        sb.append(TSI.INVENTORY_CMM);
//        sb.append("\n");
//        
//        sb.append("TGWTF");
//        sb.append(",");
//        sb.append(TSI.INVENTORY_TGWTF);
//        sb.append("\n");
//        sb.append("TIFY");
//        sb.append(",");
//        sb.append(TSI.INVENTORY_TIFY);
//        sb.append("\n");
//        sb.append("TIFU2");
//        sb.append(",");
//        sb.append(TSI.INVENTORY_TIFY2);
//        sb.append("\n");
//        sb.append("IIHY");
//        sb.append(",");
//        sb.append(TSI.INVENTORY_IIHY);
//        sb.append("\n");
//        
//        pw.write(sb.toString());
//        pw.close();
//
//    }
//
//    
//    
//    
//    
    
    
    
}
