/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pos.remade;

import business.addToBillHelper;
import business.checkForStockHelper;
import business.deleteHelper;
import business.TSI;
import java.awt.Component;
import java.awt.Desktop;
import java.awt.print.PrinterJob;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.List;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.beans.binding.StringBinding;

/**
 *
 * @author ianschrauth
 */
public class POSScreenUser extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public POSScreenUser() {

        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        ciatwe = new javax.swing.JButton();
        piate = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        price = new javax.swing.JLabel();
        jButton19 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        custom = new javax.swing.JTextField();
        jButton20 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Book title", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table);

        ciatwe.setText("CIATW");
        ciatwe.setEnabled(false);
        ciatwe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ciatweActionPerformed(evt);
            }
        });

        piate.setText("PIATW");
        piate.setEnabled(false);
        piate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                piateActionPerformed(evt);
            }
        });

        jButton3.setText("BIATW");
        jButton3.setEnabled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton6.setText("VBAB1");
        jButton6.setEnabled(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("VBABss");
        jButton7.setEnabled(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton9.setText("TUIFU");
        jButton9.setEnabled(false);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton15.setText("CMM");
        jButton15.setEnabled(false);
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jButton17.setText("Delete");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        price.setText("0.00");

        jButton19.setText("VBAB2");
        jButton19.setEnabled(false);
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });

        jButton4.setText("Pay now");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton18.setText("IIHU");
        jButton18.setEnabled(false);
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        jButton8.setText("Add to total");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel1.setText("Custom price");

        custom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customActionPerformed(evt);
            }
        });

        jButton20.setText("TIFU2");
        jButton20.setEnabled(false);
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });

        jButton10.setText("VBAB3");
        jButton10.setEnabled(false);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton5.setText("FPK");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton21.setText("TGWIF");
        jButton21.setEnabled(false);
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });

        jMenu2.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Admin menu (BETA)");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_BACK_SPACE, 0));
        jMenuItem2.setText("Clear");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setText("Finalize event");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("Stock");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuItem11.setText("Reprint receipt");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem11);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Discounts list");

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("100%");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton9)
                                    .addComponent(jButton21))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton18))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton19))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(piate)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(ciatwe, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton3)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton7))))
                            .addComponent(jButton8)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(custom, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(price)
                            .addGap(44, 44, 44)
                            .addComponent(jButton4)
                            .addGap(48, 48, 48))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap()))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5)
                        .addGap(16, 16, 16))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(piate, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ciatwe, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(custom, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton17)
                    .addComponent(jButton5))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //https://docs.google.com/spreadsheets/u/0/d/1Nvarm3CjxAKuccnEp_RqUfrvKwUiXLsd_vJ8Ts5rap0/export?format=csv&id=1Nvarm3CjxAKuccnEp_RqUfrvKwUiXLsd_vJ8Ts5rap0&gid=0


//   static int arc = 0, customP = 0, piatw = 0, cmm = 0, tifu2c = 0, ciatw = 0, biatw = 0, vbab1 = 0, vbab2 = 0, vbab3 = 0, tifu = 0, tifu2 = 0, tgwtf = 0, dil = 0, bella = 0, nia = 0, iihy = 0 , vbabss = 0;
//    static int Sarc, Ssiatw, Spiatw, Scmm, Stifu2c, Sciatw, Sbiatw, Svbab1, Svbab2, Svbab3, Stifu, Stifu2, Stgwtf, Sdil, Sbella, Snia, Siihy, Svbabss;

    static String name;

    int pl = -1;
    static double allSales = 0.00;



    Object[] row;
    int NOR = 0;
    double change2 = Math.round(allSales * 1000.0) / 1000.0;
   
    
    prices p =  new prices();

    private void piateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_piateActionPerformed
      
  DefaultTableModel model = (DefaultTableModel) table.getModel();
        
        
        addToBillHelper atbHelper = new addToBillHelper();

        atbHelper.addToTable(model, "PIATW", p.pricePIATW, price);
       
 atbHelper.changeStock(TSI.STOCK_PIATW, piate, TSI.INVENTORY_PIATW);
       if (TSI.INVENTORY_PIATW == 0) {
            piate.setEnabled(false);


        }
    }//GEN-LAST:event_piateActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        // model,  numRows2,  row,  priceToRemove,  masterPrice,  CopiesOfbooksSold,  stockAmmt,  button,  priceLabel
        
        

        int numRows2 = table.getSelectedRows().length;

        int row = table.getSelectedRow();

        String numToDel = table.getValueAt(row, 1).toString();
        
        double priceToRemove = Double.parseDouble(numToDel);

 System.out.println(priceToRemove);

        

        switch (table.getModel().getValueAt(row, 0).toString()) {
            case "PIATW":
                    deleteHelper.delete(model, numRows2, row, priceToRemove, TSI.BILL_TOTAL, TSI.INVENTORY_PIATW, TSI.STOCK_PIATW, piate, price);
              break;

            case "CIATW":
                   deleteHelper.delete(model, numRows2, row, priceToRemove, TSI.BILL_TOTAL, TSI.INVENTORY_CIATW, TSI.STOCK_CIATW, ciatwe, price);
              break;

            case "VBAB1":
            deleteHelper.delete(model, numRows2, row, priceToRemove, TSI.BILL_TOTAL, TSI.INVENTORY_VBAB1, TSI.STOCK_VBAB1, jButton6, price);
              break;

            case "VBAB2":
               deleteHelper.delete(model, numRows2, row, priceToRemove, TSI.BILL_TOTAL, TSI.INVENTORY_VBAB2, TSI.STOCK_VBAB2, jButton19, price);
              break;

            case "VBAB3":
                deleteHelper.delete(model, numRows2, row, priceToRemove, TSI.BILL_TOTAL, TSI.INVENTORY_VBAB3, TSI.STOCK_VBAB3, jButton10, price);
              break;

            case "BIATW":
            deleteHelper.delete(model, numRows2, row, priceToRemove, TSI.BILL_TOTAL, TSI.INVENTORY_BIATW, TSI.STOCK_BIATW, jButton3, price);
              break;

            case "TIFY":
                  deleteHelper.delete(model, numRows2, row, priceToRemove, TSI.BILL_TOTAL, TSI.INVENTORY_TIFY, TSI.STOCK_TIFY, jButton9, price);

                        break;

            case "TIFY2":
        deleteHelper.delete(model, numRows2, row, priceToRemove, TSI.BILL_TOTAL, TSI.INVENTORY_TIFY2, TSI.STOCK_TIFY2, jButton20, price);

              break;

            case "VBABss":
        deleteHelper.delete(model, numRows2, row, priceToRemove, TSI.BILL_TOTAL, TSI.INVENTORY_VBABSS, TSI.STOCK_VBABSS, jButton18, price);
              break;

            case "CMM":
            deleteHelper.delete(model, numRows2, row, priceToRemove, TSI.BILL_TOTAL, TSI.INVENTORY_CMM, TSI.STOCK_CMM, jButton15, price);
              break;

            case "TGWTF":
                deleteHelper.delete(model, numRows2, row, priceToRemove, TSI.BILL_TOTAL, TSI.INVENTORY_TGWTF, TSI.STOCK_TGWTF, jButton21, price);
              break;

           case "IIHY":
              deleteHelper.delete(model, numRows2, row, priceToRemove, TSI.BILL_TOTAL, TSI.INVENTORY_IIHY, TSI.STOCK_IIHY, jButton7, price);
              break;
 
            default:
                Component frame = null;
            JOptionPane.showMessageDialog(frame, "Nothing is selcted.");
            break;
            
            
        }
    


        model.removeRow(row);
        model.fireTableDataChanged();

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton17ActionPerformed
    private void ciatweActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ciatweActionPerformed
   DefaultTableModel model = (DefaultTableModel) table.getModel();
        
        
        addToBillHelper atbHelper = new addToBillHelper();

        atbHelper.addToTable(model, "CIATW", p.priceCIATW, price);
       
 atbHelper.changeStock(TSI.STOCK_CIATW, ciatwe, TSI.INVENTORY_CIATW);
  if (TSI.INVENTORY_CIATW == 0) {
            ciatwe.setEnabled(false);


        }
    }//GEN-LAST:event_ciatweActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
  DefaultTableModel model = (DefaultTableModel) table.getModel();
        
        
        addToBillHelper atbHelper = new addToBillHelper();

        atbHelper.addToTable(model, "VBAB1", p.priceVBABo, price);
       
 atbHelper.changeStock(TSI.STOCK_VBAB1, jButton3, TSI.INVENTORY_VBAB1);

  if (TSI.INVENTORY_VBAB1 == 0) {
            jButton3.setEnabled(false);


        }
// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        dispose();
        new adminMenu().setVisible(true);        // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed
    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        DefaultTableModel model = (DefaultTableModel) table.getModel();

        TSI.BILL_TOTAL = 0.00;
        price.setText("0.00");
        model.setRowCount(0);
        model.fireTableDataChanged();
        model.fireTableStructureChanged();
        // TODO add your handling code here:
        ;
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        BufferedReader in = null;
        BufferedWriter writer = null;

        try {
            adminMenu admin = new adminMenu();
            DefaultTableModel model = (DefaultTableModel) table.getModel();
            String st = "names.csv";
            writer = new BufferedWriter(new FileWriter(st));
            in = new BufferedReader(new FileReader(st));
            String s;
            String lineToRemove = "";
            String currentLine = null;

            while ((s = in.readLine()) != null) {
                for (int i = 0; i < s.length(); i++) {
                    if (s.contains(lineToRemove)) {
                        String trimmedLine = currentLine.trim();
                        if (trimmedLine.equals(lineToRemove)) {
                            continue;
                        }
                        writer.write(currentLine + System.getProperty("line.separator"));
                        writer.close();
                        break;
                    }
                }
            }
            try (BufferedWriter bw = new BufferedWriter(new FileWriter("finalize.txt", true))) {
                bw.write("FINALIZING COMPLETE! THIS IS YOUR PROGRESS: \r\n \r\n HOW MUCH YOU MADE: " + admin.all + " \r\n PIATW: " + TSI.INVENTORY_PIATW
                        + "\r\n CIATW: " + TSI.INVENTORY_CIATW + "\r\n BIATW: " + TSI.INVENTORY_BIATW + "\r\n VBAB1: " + TSI.INVENTORY_VBAB1 + "\r\n VBAB2: " + TSI.INVENTORY_VBAB2
                        + "\r\n VBAB3: " + TSI.INVENTORY_VBAB3 + "\r\n TIFU: " + TSI.INVENTORY_TIFY + "\r\n TIFU2: " + TSI.INVENTORY_TIFY2 + "\r\n TGWTF: " + TSI.INVENTORY_TGWTF
                        + "\r\n IIHU: " + TSI.INVENTORY_IIHY +   "\r\n CMM: " + TSI.INVENTORY_CMM);

                Desktop.getDesktop().print(new File("finalize.txt"));
                createStockCSV();

                System.out.println("Done");

                // TODO add your handling code here:
            } catch (IOException ex) {
                Logger.getLogger(POSScreenUser.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(POSScreenUser.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(POSScreenUser.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                in.close();
            } catch (IOException ex) {
                Logger.getLogger(POSScreenUser.class.getName()).log(Level.SEVERE, null, ex);
            }
        }


    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        DefaultTableModel model = (DefaultTableModel) table.getModel();

        model.setRowCount(0);
        model.fireTableDataChanged();
        model.fireTableStructureChanged();

        if (TSI.BILL_TOTAL == 0) {
            Component frame = null;
            JOptionPane.showMessageDialog(frame, "Total is Zero. No need to cash out.");
            model.setRowCount(0);
            TSI.BILL_TOTAL = 0.00;
            price.setText("0.00");
            model.fireTableDataChanged();
        } else {

            new payment2().setVisible(true);
            setVisible(false);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
           
  DefaultTableModel model = (DefaultTableModel) table.getModel();
        
        
        addToBillHelper atbHelper = new addToBillHelper();

        atbHelper.addToTable(model, "CUSTOM PRICE", Double.parseDouble(custom.getText()), price);
       
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void customActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        new inventory().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        DefaultTableModel model = (DefaultTableModel) table.getModel();

        checkForStockHelper.checkForStock(TSI.INVENTORY_PIATW, piate);
        checkForStockHelper.checkForStock(TSI.INVENTORY_CIATW, ciatwe);
        checkForStockHelper.checkForStock(TSI.INVENTORY_BIATW, jButton3);
        checkForStockHelper.checkForStock(TSI.INVENTORY_VBAB1, jButton6);
        checkForStockHelper.checkForStock(TSI.INVENTORY_VBAB2, jButton19);
        checkForStockHelper.checkForStock(TSI.INVENTORY_VBAB3, jButton10);
        checkForStockHelper.checkForStock(TSI.INVENTORY_CMM, jButton15);
        checkForStockHelper.checkForStock(TSI.INVENTORY_TIFY, jButton9);
        checkForStockHelper.checkForStock(TSI.INVENTORY_TIFY2, jButton20);
        checkForStockHelper.checkForStock(TSI.INVENTORY_IIHY, jButton18);
        checkForStockHelper.checkForStock(TSI.INVENTORY_TGWTF, jButton21);
        checkForStockHelper.checkForStock(TSI.INVENTORY_VBABSS, jButton7);

    

        
    }//GEN-LAST:event_formWindowOpened

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        DefaultTableModel model = (DefaultTableModel) table.getModel();

        if (model.getRowCount() == 0) {

            TSI.BILL_TOTAL = 0.00;
            price.setText("0.00");

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        int col0 = 0;
        int col1 = 1;
        

        int numRows2 = table.getSelectedRows().length;
        int row = table.getSelectedRow();
        Component frame = null;
        if (table.getModel().getValueAt(row, 0).equals("0.00")) {
            JOptionPane.showMessageDialog(frame, "You already set it to free. delete \r\n the book and re-add it to take off the promo.");
        }
        for (int count = 0; count < model.getRowCount(); count++) {

            TSI.BILL_TOTAL -= (Double) table.getValueAt(row, 1);;
    
            System.out.println(TSI.BILL_TOTAL);
            price.setText(Double.toString(TSI.BILL_TOTAL));

            model.fireTableDataChanged();

            break;

        }
        table.getModel().setValueAt((Double) 0.00, row, 1);

// TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        new reprint().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        DefaultTableModel model = (DefaultTableModel) table.getModel();

        String contentForReceipt = "IAN'S BOOK SIGNING RECEIPT \r\n Total: $0.00.  \r\n Was $" + TSI.BILL_TOTAL;

        try (BufferedWriter bw = new BufferedWriter(new FileWriter("receipt100.txt"))) {
            bw.write(contentForReceipt);

            //Desktop.getDesktop().print(new File("receipt100.txt"));
            System.out.println("Done");

            model.setRowCount(0);
            TSI.BILL_TOTAL = 0.00;
            price.setText("0.00");
            model.fireTableDataChanged();

        } catch (IOException ex) {
            Logger.getLogger(POSScreenUser.class.getName()).log(Level.SEVERE, null, ex);

        }        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
       
  DefaultTableModel model = (DefaultTableModel) table.getModel();
        
        
        addToBillHelper atbHelper = new addToBillHelper();

        atbHelper.addToTable(model, "TGWTF", p.priceTGWTF, price);
       
 atbHelper.changeStock(TSI.STOCK_TGWTF, jButton21, TSI.INVENTORY_TGWTF);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
           DefaultTableModel model = (DefaultTableModel) table.getModel();
        
        
        addToBillHelper atbHelper = new addToBillHelper();

        atbHelper.addToTable(model, "CMM", p.priceCMM, price);
       
 atbHelper.changeStock(TSI.STOCK_CMM, jButton15, TSI.INVENTORY_CMM);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
             DefaultTableModel model = (DefaultTableModel) table.getModel();
        
        
        addToBillHelper atbHelper = new addToBillHelper();

        atbHelper.addToTable(model, "VBAB3", p.priceVBABth, price);
       
 atbHelper.changeStock(TSI.STOCK_VBAB3, jButton10, TSI.INVENTORY_VBAB3);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
            DefaultTableModel model = (DefaultTableModel) table.getModel();
        
        
        addToBillHelper atbHelper = new addToBillHelper();

        atbHelper.addToTable(model, "TIFY", p.priceTIFU, price);
       
 atbHelper.changeStock(TSI.STOCK_TIFY, jButton9, TSI.INVENTORY_TIFY);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
      DefaultTableModel model = (DefaultTableModel) table.getModel();
        
        
        addToBillHelper atbHelper = new addToBillHelper();

        atbHelper.addToTable(model, "TIFY2", p.priceTIFU2, price);
       
 atbHelper.changeStock(TSI.STOCK_TIFY2, jButton20, TSI.INVENTORY_TIFY2);
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
      DefaultTableModel model = (DefaultTableModel) table.getModel();
        
        
        addToBillHelper atbHelper = new addToBillHelper();

        atbHelper.addToTable(model, "VBABSS", p.priceIIHU, price);
       
 atbHelper.changeStock(TSI.STOCK_IIHY, jButton7, TSI.INVENTORY_IIHY);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        DefaultTableModel model = (DefaultTableModel) table.getModel();

        addToBillHelper atbHelper = new addToBillHelper();

        atbHelper.addToTable(model, "VBAB1", p.priceIIHU, price);

        atbHelper.changeStock(TSI.STOCK_IIHY, jButton6, TSI.INVENTORY_IIHY);
  if (TSI.INVENTORY_VBAB1 == 0) {
            jButton6.setEnabled(false);


        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
      DefaultTableModel model = (DefaultTableModel) table.getModel();
        
        
        addToBillHelper atbHelper = new addToBillHelper();

        atbHelper.addToTable(model, "IIHY", p.priceIIHU, price);
       
 atbHelper.changeStock(TSI.STOCK_IIHY, jButton18, TSI.INVENTORY_IIHY);
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
      DefaultTableModel model = (DefaultTableModel) table.getModel();
        
        
        addToBillHelper atbHelper = new addToBillHelper();

        atbHelper.addToTable(model, "VBAB2", p.priceVBABt, price);
       
 atbHelper.changeStock(TSI.STOCK_VBAB2, jButton19, TSI.INVENTORY_VBAB2);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton19ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(POSScreenUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(POSScreenUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(POSScreenUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(POSScreenUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new POSScreenUser().setVisible(true);

            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton ciatwe;
    private javax.swing.JTextField custom;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton3;
    public static javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JButton piate;
    public javax.swing.JLabel price;
    public static javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables

    private void createStockCSV() throws FileNotFoundException {
        
            java.util.Date date = new java.util.Date();

        
        PrintWriter pw = new PrintWriter(new File("PastStock" + date + ".csv"));
        StringBuilder sb = new StringBuilder();
        sb.append("BIATW");
        sb.append(",");
        sb.append(TSI.INVENTORY_BIATW);
        sb.append("\n");
        sb.append("CIATW");
        sb.append(",");
        sb.append(TSI.INVENTORY_CIATW);
        sb.append("\n");
        sb.append("PIATW");
        sb.append(",");
        sb.append(TSI.INVENTORY_PIATW);
        sb.append("\n");
        sb.append("VBAB1");
        sb.append(",");
        sb.append(TSI.INVENTORY_VBAB1);
        sb.append("\n");
        sb.append("VBAB2");
        sb.append(",");
        sb.append(TSI.INVENTORY_VBAB2);
        sb.append("\n");
        sb.append("VBAB3");
        sb.append(",");
        sb.append(TSI.INVENTORY_VBAB3);
        sb.append("\n");
        sb.append("VBABSS");
        sb.append(",");
        sb.append(TSI.INVENTORY_VBABSS);
        sb.append("\n");
        sb.append("CMM");
        sb.append(",");
        sb.append(TSI.INVENTORY_CMM);
        sb.append("\n");
        
        sb.append("TGWTF");
        sb.append(",");
        sb.append(TSI.INVENTORY_TGWTF);
        sb.append("\n");
        sb.append("TIFY");
        sb.append(",");
        sb.append(TSI.INVENTORY_TIFY);
        sb.append("\n");
        sb.append("TIFU2");
        sb.append(",");
        sb.append(TSI.INVENTORY_TIFY2);
        sb.append("\n");
        sb.append("IIHY");
        sb.append(",");
        sb.append(TSI.INVENTORY_IIHY);
        sb.append("\n");
        
        pw.write(sb.toString());
        pw.close();

    }

    
    
    
    
}
